In [1]:
import pandas as pd

In [14]:
dd = pd.read_csv("datasets/bad_daraz_dataset.csv")
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [15]:
dd["price"] = pd.to_numeric(dd["price"], errors = "coerce")
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [20]:
# Z-score method

mean = dd["price"].mean() #1853.84
std = dd["price"].std()  #2279.11

dd["z_score"] = (dd["price"] - mean)/std
dd

#z_score >  2 = Outliers
#z_score < 2  = Not-Outliers

outliers = dd[dd["z_score"].abs() > 2]
outliers

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,z_score
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633

In [5]:
#quartiles
median = dd["price"].quantile(0.50)
q1 = dd["price"].quantile(0.25)
q3 = dd["price"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - (1.5 * iqr)  #-2550
upper_bound = q3 + (1.5 * iqr)   #8250

outliers = dd[(dd["price"] < lower_bound) | (dd["price"] > upper_bound)]
print(outliers)

   product_id product_name     category    price discount_percent  rating  \
0           1       Laptop  Electronics  75000.0               10     4.8
6           7       Laptop  Electronics  75000.0               10     4.8

  stock   seller       city brand gender_target age  reviews
0    25  TechHub  Kathmandu  Dell        Unisex  25      120
6    25  TechHub  Kathmandu  Dell        Unisex  25      120

In [6]:
len(outliers)

2

In [7]:
#fixing outliers using Mean/Median
dd.loc[(dd["price"] < lower_bound) | (dd["price"] > upper_bound), "price"] = median
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,2500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,2500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [17]:
#fixing outliers using winsorization(capping) ---> clip 
dd["price"].clip(lower_bound,upper_bound)

0     8250.0
1        NaN
2     3500.0
3     1500.0
4     5500.0
5     4200.0
6     8250.0
7        NaN
8     1800.0
9     1800.0
10    2500.0
11    2500.0
12     800.0
13   -2500.0
14   -2500.0
Name: price, dtype: float64

0     0.283511
1          NaN
2     0.722278
3    -0.155256
4     1.599812
5     1.029415
6     0.283511
7          NaN
8    -0.023626
9    -0.023626
10    0.283511
11    0.283511
12   -0.462393
13   -1.910324
14   -1.910324
Name: price, dtype: float64