In [1]:
import pandas as pd

In [2]:
dd = pd.read_csv("datasets/bad_daraz_dataset.csv")
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [3]:
dd["price"] = pd.to_numeric(dd["price"], errors = "coerce")
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [4]:
# Z-score method

mean = dd["price"].mean() #1853.84
std = dd["price"].std()  #2279.11

dd["z_score"] = (dd["price"] - mean)/std
dd

#z_score >  2 = Outliers
#z_score < 2  = Not-Outliers

outliers = dd[dd["z_score"].abs() > 2]
outliers

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,z_score
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633

In [5]:
#quartiles
median = dd["price"].quantile(0.50)
q1 = dd["price"].quantile(0.25)
q3 = dd["price"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - (1.5 * iqr)  #-2550
upper_bound = q3 + (1.5 * iqr)   #8250

outliers = dd[(dd["price"] < lower_bound) | (dd["price"] > upper_bound)]
print(outliers)

   product_id product_name     category    price discount_percent  rating  \
0           1       Laptop  Electronics  75000.0               10     4.8
6           7       Laptop  Electronics  75000.0               10     4.8

  stock   seller       city brand gender_target age  reviews   z_score
0    25  TechHub  Kathmandu  Dell        Unisex  25      120  2.245633
6    25  TechHub  Kathmandu  Dell        Unisex  25      120  2.245633

In [6]:
len(outliers)

2

In [6]:
#fixing outliers using Mean/Median
dd.loc[(dd["price"] < lower_bound) | (dd["price"] > upper_bound), "price"] = median
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,z_score
0,1,Laptop,Electronics,2500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210,NaN
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55,-0.344410
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30,-0.416859
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80,-0.271961
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65,-0.319053
6,7,Laptop,Electronics,2500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18,NaN
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90,-0.405992
9,9,Cup,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90,-0.405992
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110,-0.380635
11,10,Haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110,-0.380635
12,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12,-0.442216
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44,-0.561756
14,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44,-0.561756

In [7]:
#fixing outliers using winsorization(capping) ---> clip 
dd["price"].clip(lower_bound,upper_bound)

0     2500.0
1        NaN
2     3500.0
3     1500.0
4     5500.0
5     4200.0
6     2500.0
7        NaN
8     1800.0
9     1800.0
10    2500.0
11    2500.0
12     800.0
13   -2500.0
14   -2500.0
Name: price, dtype: float64

In [10]:
#Grouping

for category, data in dd.groupby("category"):
    print(data)

   product_id product_name     category   price discount_percent  rating  \
4           5        Watch  Accessories  5500.0               10     4.5

          stock seller       city  brand gender_target age  reviews   z_score
4  Out of Stock  TimeX  Kathmandu  Casio          Male  28       80 -0.271961
    product_id product_name     category   price discount_percent  rating  \
0            1       Laptop  Electronics  2500.0               10     4.8
1            2        Phone  Electronics     NaN               15     4.6
5            6   Headphones  Electronics  4200.0              NaN     4.1
6            7       Laptop  Electronics  2500.0               10     4.8
8            9        Mouse  Electronics  1800.0                5     4.3
9            9          Cup  Electronics  1800.0                5     4.3
10          10     Keyboard  Electronics  2500.0                5     4.4
11          10         Haha  Electronics  2500.0                5     4.4

   stock       seller         city     brand gender_target   age  reviews  \
0     25      TechHub    Kathmandu      Dell        Unisex    25      120
1     40  GadgetNepal      Pokhara   Samsung        Unisex    30      210
5     75     AudioPro      Pokhara       JBL        Unisex   24        65
6     25      TechHub    Kathmandu      Dell        Unisex    25      120
8    NaN      TechHub    Kathmandu  Logitech        Unisex   NaN       90
9    NaN      TechHub    Kathmandu  Logitech        Unisex   NaN       90
10    35     TechHub    Kathmandu   Logitech        Unisex    21      110
11    35     TechHub    Kathmandu   Logitech        Unisex    21      110

     z_score
0   2.245633
1        NaN
5  -0.319053
6   2.245633
8  -0.405992
9  -0.405992
10 -0.380635
11 -0.380635
   product_id product_name category   price discount_percent  rating stock  \
2           3        Shoes  Fashion  3500.0               5%     4.2    60
3           4      T-Shirt  Fashion  1500.0               20     NaN   150
7           8          Bag  Fashion     NaN               12     3.9    45

       seller        city      brand gender_target     age  reviews   z_score
2  FashionHub     Itahari       Nike          Male      22       55 -0.344410
3       Style  Biratnagar     Adidas        Female  Female       30 -0.416859
7    CarryAll      Dharan  Wildcraft        Female      19       18       NaN
    product_id product_name   category   price discount_percent  rating stock  \
13          12        Chair  Furniture -2500.0               10     4.0    -5
14          12        Chair  Furniture -2500.0               10     4.0    -5

     seller      city brand gender_target      age  reviews   z_score
13  FurniCo  Lalitpur  IKEA        Unisex  Unknown       44 -0.561756
14  FurniCo  Lalitpur  IKEA        Unisex  Unknown       44 -0.561756
    product_id product_name category  price discount_percent  rating stock  \
12          11       Bottle     Home  800.0                0     5.5   100

       seller      city    brand gender_target age  reviews   z_score
12  HomeStore  Janakpur  Generic        Unisex  26       12 -0.442216

In [11]:
dd.groupby("category").get_group("Electronics")

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,z_score
0,1,Laptop,Electronics,2500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210,NaN
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65,-0.319053
6,7,Laptop,Electronics,2500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90,-0.405992
9,9,Cup,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90,-0.405992
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110,-0.380635
11,10,Haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110,-0.380635

In [16]:
My = pd.DataFrame({
    "name" : ["Ishan", "Ojha", "Messi", "Siuu", "Ronaldo"],
    "Faculty" : ["cs", "cs", "farming", "maths", "cs"],
    "age" : [21,20,37,39,41]
})

My.groupby("Faculty").get_group("cs")

for

    name  Faculty  age
2  Messi  farming   37

In [22]:
#Aggregation

dd.groupby("category")["product_name"].count()

category
Accessories    1
Electronics    8
Fashion        3
Furniture      2
Home           1
Name: product_name, dtype: int64

In [24]:
#Multiple aggegration

dd.groupby("category")["price"].agg(["max", "mean", "count"])

                max         mean  count
category
Accessories  5500.0  5500.000000      1
Electronics  4200.0  2542.857143      7
Fashion      3500.0  2500.000000      2
Furniture   -2500.0 -2500.000000      2
Home          800.0   800.000000      1

In [23]:
dd.groupby("category")["rating"].agg(["max", "mean", "count"])

             max    mean  count
category
Accessories  4.5  4.5000      1
Electronics  4.8  4.4625      8
Fashion      4.2  4.0500      2
Furniture    4.0  4.0000      2
Home         5.5  5.5000      1

In [ ]:
dd