In [21]:
import pandas as pd

In [25]:
df = pd.read_csv("datasets/Large_Dirty_Student_Dataset.csv")

In [34]:
# df.head()
df.info()
# df.describe(include="all")
# df.shape

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          100 non-null    int64
 1   Name        100 non-null    str
 2   Age         87 non-null     str
 3   Marks       91 non-null     float64
 4   Attendance  78 non-null     float64
 5   City        100 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 4.8 KB

In [30]:
#Duplicate Rows
df.duplicated().sum()

np.int64(3)

In [31]:
#Remove Duplicates
df.drop_duplicates(inplace=True)

In [32]:
#Check if duplicates removed or not
df.duplicated().sum()

np.int64(0)

In [33]:
#Data Types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          100 non-null    int64
 1   Name        100 non-null    str
 2   Age         87 non-null     str
 3   Marks       91 non-null     float64
 4   Attendance  78 non-null     float64
 5   City        100 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 4.8 KB

In [35]:
#Handle Data Types
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [36]:
#Inconsistent Values
df["City"] = df["City"].str.strip().str.title()

In [37]:
#check missing values
df.isnull().sum()

ID             0
Name           0
Age           22
Marks          9
Attendance    22
City           0
dtype: int64

In [38]:
#Handle missing values
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].median())

In [39]:
#Check invalid values (age smaller than 0)
df[df["Age"] < 0]

    ID       Name  Age  Marks  Attendance       City
0    1   Student1 -3.0   67.0        95.0   Lalitpur
2    3   Student3 -3.0   90.0        65.0    Pokhara
22  23  Student23 -3.0   67.0        95.0    Pokhara
24  25  Student25 -3.0   72.0        85.0  Kathmandu
30  31  Student31 -3.0   55.0        95.0  Kathmandu
37  38  Student38 -3.0  105.0        95.0  Kathmandu
43  44  Student44 -3.0   67.0        85.0    Pokhara
53  54  Student54 -3.0   90.0        85.0    Pokhara
59  60  Student60 -3.0   67.0        85.0    Pokhara
62  63  Student63 -3.0   67.0        85.0  Kathmandu
69  70  Student70 -3.0   81.0        85.0  Kathmandu
70  71  Student71 -3.0   55.0        75.0  Kathmandu
77  78  Student78 -3.0   55.0        85.0    Pokhara
82  83  Student83 -3.0   67.0       120.0    Pokhara

In [40]:
#Removing age smaller than 0
df = df[df["Age"] >= 0]

In [42]:
##Check invalid values (Marks greater than 100)
df[df["Marks"] > 100]

    ID       Name   Age  Marks  Attendance       City
18  19  Student19  20.0  105.0        75.0  Kathmandu
23  24  Student24  18.0  105.0        65.0    Pokhara
28  29  Student29  22.0  105.0       120.0   Lalitpur
39  40  Student40  21.0  105.0        75.0  Kathmandu
61  62  Student62  19.0  105.0        85.0    Pokhara
65  66  Student66  21.0  105.0        75.0  Kathmandu
89  90  Student90  18.0  105.0        85.0    Pokhara

In [43]:
#Check invalid values (attendence greater than 100)
df[df["Attendance"] > 100]

     ID        Name   Age      Marks  Attendance       City
1     2    Student2  18.0   55.00000       120.0  Kathmandu
7     8    Student8  18.0   90.00000       120.0    Pokhara
10   11   Student11  19.0   55.00000       120.0  Kathmandu
12   13   Student13  19.0   90.00000       120.0   Lalitpur
20   21   Student21  19.0   72.00000       120.0  Kathmandu
28   29   Student29  22.0  105.00000       120.0   Lalitpur
40   41   Student41  19.0   76.56044       120.0  Kathmandu
60   61   Student61  18.0   76.56044       120.0  Kathmandu
63   64   Student64  19.0   90.00000       120.0  Kathmandu
72   73   Student73  21.0   81.00000       120.0    Pokhara
81   82   Student82  20.0   90.00000       120.0    Pokhara
87   88   Student88  19.0   67.00000       120.0  Kathmandu
90   91   Student91  19.0   81.00000       120.0  Kathmandu
91   92   Student92  19.0   67.00000       120.0    Pokhara
94   95   Student95  20.0   81.00000       120.0   Lalitpur
96   97   Student97  19.0   90.00000       120.0    Pokhara
99  100  Student100  19.0   81.00000       120.0  Kathmandu

In [44]:
#Remove or correct them
df = df[df["Marks"] <= 100]
df = df[df["Attendance"] <= 100]

In [46]:
#Detect outliers

Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

outliers = df[(df["Marks"] < lower) | (df["Marks"] > upper)]
print(outliers)

Empty DataFrame
Columns: [ID, Name, Age, Marks, Attendance, City]
Index: []

In [47]:
df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.DataFrame'>
Index: 63 entries, 3 to 98
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          63 non-null     int64
 1   Name        63 non-null     str
 2   Age         63 non-null     float64
 3   Marks       63 non-null     float64
 4   Attendance  63 non-null     float64
 5   City        63 non-null     str
dtypes: float64(3), int64(1), str(2)
memory usage: 3.4 KB

np.int64(0)

In [48]:
df.to_csv("Cleaned_Student_Dataset.csv", index=False)